services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ..:/src:cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined